[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
verbosity = 3
show_progress = true
auto_detect_remappings = false
ignored_warnings_from = ["dependencies/"]
optimize = true
optimizer_runs = 200
remappings = [
    "@solady/=dependencies/solady-0.1.26/src/",
    "@forge-std/=dependencies/forge-std-1.14.0/src/",
    "@origin-dollar/=dependencies/origin-dollar-1.0.0/contracts/contracts/",
    "@solmate/=dependencies/solmate-89365b880c4f3c786bdd453d4b8e8fe410344a69/src/",
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-4.4.2-4.4.2/contracts/",
]

[lint]
lint_on_build = false

[invariant]
runs = 20
depth = 500
show_metrics = true
call_override = false
fail_on_revert = true
include_storage = true
shrink_run_limit = 50_000
dictionary_weight = 80
include_push_bytes = true
max_assume_rejects = 10_000

[dependencies]
solady = "0.1.26"
forge-std = "1.14.0"
solmate = "89365b880c4f3c786bdd453d4b8e8fe410344a69"
"origin-dollar" = { version = "1.0.0", git = "git@github.com:OriginProtocol/origin-dollar.git", rev = "29639b3f95b9ee4080fbd53a032d71dc4dcabb7e" }
"openzeppelin-contracts-4.4.2" = { version = "4.4.2", git = "git@github.com:OpenZeppelin/openzeppelin-contracts.git", rev = "b53c43242fc9c0e435b66178c3847c4a1b417cc1" }


[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
